### ISSUE TITLE
MIS builder 4.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/mis-builder#371]
I'm going to prepare a 13.0-4.0-staging branch with some minor backward-incompatible changes and other improvements

- [x] multi-company support (#327, #374)
- [x] use a parent_state field to ignore cancel entries and report on draft move-line-like tables (#344)
- [x] improvements to budget items (labels #338, optional overlap #339, inverse compute on balance for easier input #337)
