### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/mis-builder#471]
# Todo

This repo branched 16.0 from 15.0 with all modules marked installable=False. 
To migrate set module installable=True in manifest and add migration commits.
See https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0 for additional migration tips.

# Modules to migrate

- [ ] mis_builder - By @adrienpeiffer - #472
- [ ] mis_builder_budget
- [ ] mis_builder_demo

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by dzungtran89** [comment]
- mis_builder_budget: https://github.com/OCA/mis-builder/pull/488

**Comment by dzungtran89** [comment]
- mis_builder_demo: https://github.com/OCA/mis-builder/pull/489
